[package]
name = "mimesis-bin"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
mimesis = { path = "..", default-features = false }
image = "0.25.6"
clap = { version = "4.5.38", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.22"
rayon = "1.10.0"
anyhow = "1.0.98"
geo = "0.30.0"

[features]
background-remover = ["mimesis/background-remover"]