[package]
name = "mimesis-bin"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
mimesis = { path = ".." }
imageproc = "0.25.0"
image = "0.25.6"
geo = "0.30.0"
clap = { version = "4.5.38", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
toml = "0.8.22"
serde_yaml = "0.9.34+deprecated"